# Generated by Django 4.2.9 on 2026-10-02 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_no', models.CharField(max_length=40, unique=True, verbose_name='交接单号')),
                ('status', models.CharField(choices=[('draft', '编制中'), ('submitted', '待确认'), ('completed', '已完成'), ('returned', '已退回'), ('cancelled', '已作废')], default='draft', max_length=20, verbose_name='状态')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='当前冻结版本')),
                ('responsible_party', models.CharField(choices=[('transferor', '移交人'), ('receiver', '接收人')], default='transferor', max_length=20, verbose_name='最终责任归属')),
                ('difference_reason', models.TextField(blank=True, verbose_name='差异原因')),
                ('transfer_note', models.TextField(blank=True, verbose_name='移交备注')),
                ('frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='最近冻结时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='首次冻结时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='退回时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='作废时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_received', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('transferor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_given', to=settings.AUTH_USER_MODEL, verbose_name='移交人')),
            ],
            options={
                'verbose_name': '交接清单',
                'verbose_name_plural': '交接清单',
                'db_table': 'wh_handover_list',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128, unique=True, verbose_name='幂等键')),
                ('scope', models.CharField(max_length=50, verbose_name='业务域')),
                ('request_path', models.CharField(blank=True, max_length=200, verbose_name='请求路径')),
                ('request_hash', models.CharField(blank=True, max_length=64, verbose_name='请求指纹')),
                ('response_body', models.JSONField(blank=True, null=True, verbose_name='响应内容')),
                ('status_code', models.PositiveIntegerField(default=0, verbose_name='响应状态码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次提交时间')),
                ('handover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to='warehouse.handoverlist', verbose_name='关联交接单')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': '幂等记录',
                'verbose_name_plural': '幂等记录',
                'db_table': 'wh_idempotency_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建清单'), ('freeze', '冻结清单'), ('item_confirm', '逐项确认'), ('return', '退回修订'), ('complete', '完成交接'), ('cancel', '作废清单')], max_length=20, verbose_name='事件类型')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='新状态')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='事件版本')),
                ('detail', models.TextField(blank=True, verbose_name='事件详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='warehouse.handoverlist', verbose_name='交接清单')),
            ],
            options={
                'verbose_name': '交接事件',
                'verbose_name_plural': '交接事件',
                'db_table': 'wh_handover_event',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HandoverCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='更正原因')),
                ('quantity_change', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='数量更正(正补负冲)')),
                ('correct_seal_no', models.CharField(blank=True, max_length=100, verbose_name='更正后封签号')),
                ('correct_location', models.CharField(blank=True, max_length=100, verbose_name='更正后存放位置')),
                ('detail', models.TextField(blank=True, verbose_name='更正说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='更正时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_handover_corrections', to=settings.AUTH_USER_MODEL, verbose_name='更正人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handover_corrections', to='warehouse.goods', verbose_name='相关物资')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='warehouse.handoverlist', verbose_name='交接清单')),
            ],
            options={
                'verbose_name': '交接更正记录',
                'verbose_name_plural': '交接更正记录',
                'db_table': 'wh_handover_correction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('frozen_at', models.DateTimeField(auto_now_add=True, verbose_name='冻结时间')),
                ('item_count', models.PositiveIntegerField(verbose_name='物资行数')),
                ('item_snapshot', models.JSONField(default=list, verbose_name='清单快照')),
                ('remark', models.TextField(blank=True, verbose_name='冻结说明')),
                ('frozen_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_handover_versions', to=settings.AUTH_USER_MODEL, verbose_name='冻结人')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='warehouse.handoverlist', verbose_name='交接清单')),
            ],
            options={
                'verbose_name': '交接版本',
                'verbose_name_plural': '交接版本',
                'db_table': 'wh_handover_version',
                'ordering': ['version'],
                'unique_together': {('handover', 'version')},
            },
        ),
        migrations.CreateModel(
            name='HandoverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='冻结版本')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='移交数量')),
                ('expected_seal_no', models.CharField(blank=True, max_length=100, verbose_name='封签号')),
                ('expected_location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='确认数量')),
                ('actual_seal_no', models.CharField(blank=True, max_length=100, verbose_name='确认封签号')),
                ('actual_location', models.CharField(blank=True, max_length=100, verbose_name='确认存放位置')),
                ('confirm_result', models.CharField(choices=[('pending', '待确认'), ('matched', '一致'), ('different', '有差异')], default='pending', max_length=20, verbose_name='逐项确认结果')),
                ('difference_reason', models.CharField(blank=True, max_length=300, verbose_name='差异说明')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='逐项确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_handover_items', to=settings.AUTH_USER_MODEL, verbose_name='逐项确认人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handover_items', to='warehouse.goods', verbose_name='物资')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.handoverlist', verbose_name='交接清单')),
            ],
            options={
                'verbose_name': '交接清单物资行',
                'verbose_name_plural': '交接清单物资行',
                'db_table': 'wh_handover_item',
                'ordering': ['id'],
                'unique_together': {('handover', 'goods', 'version')},
            },
        ),
    ]
