# Generated by Django 4.2.9 on 2026-10-02 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handoff_no', models.CharField(max_length=40, unique=True, verbose_name='交接单号')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='清单版本')),
                ('status', models.CharField(choices=[('draft', '待冻结'), ('frozen', '已冻结待确认'), ('returned', '已退回修订'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='冻结时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='幂等键')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handoffs_as_custodian', to=settings.AUTH_USER_MODEL, verbose_name='最终责任人')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handoffs_as_receiver', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('transferor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handoffs_as_transferor', to=settings.AUTH_USER_MODEL, verbose_name='移交人')),
            ],
            options={
                'verbose_name': '物资交接清单',
                'verbose_name_plural': '物资交接清单',
                'db_table': 'wh_handoff_list',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=200, verbose_name='物资名称')),
                ('goods_code', models.CharField(max_length=50, verbose_name='物资编码')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='移交数量')),
                ('seal_no', models.CharField(blank=True, max_length=100, verbose_name='封签号')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实收数量')),
                ('actual_seal_no', models.CharField(blank=True, max_length=100, verbose_name='实查封签号')),
                ('actual_location', models.CharField(blank=True, max_length=100, verbose_name='实查存放位置')),
                ('item_status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('disputed', '有差异')], default='pending', max_length=20, verbose_name='确认状态')),
                ('difference_reason', models.TextField(blank=True, verbose_name='差异原因')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handoff_items', to='warehouse.goods', verbose_name='物资')),
                ('handoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.handofflist', verbose_name='交接清单')),
            ],
            options={
                'verbose_name': '交接清单明细',
                'verbose_name_plural': '交接清单明细',
                'db_table': 'wh_handoff_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HandoffEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='发生时版本')),
                ('action', models.CharField(choices=[('created', '创建清单'), ('frozen', '冻结清单'), ('item_confirmed', '逐项确认'), ('returned', '退回修订'), ('completed', '完成交接'), ('rejected', '生效被拒'), ('amended', '更正记录')], max_length=20, verbose_name='事件类型')),
                ('detail', models.TextField(blank=True, verbose_name='事件详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('handoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='warehouse.handofflist', verbose_name='交接清单')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoff_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '交接事件',
                'verbose_name_plural': '交接事件',
                'db_table': 'wh_handoff_event',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HandoffCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='更正后版本')),
                ('reason', models.TextField(verbose_name='更正原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='更正时间')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handoff_corrections', to='warehouse.goods', verbose_name='涉及物资')),
                ('handoff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='warehouse.handofflist', verbose_name='交接清单')),
                ('new_custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections_to', to=settings.AUTH_USER_MODEL, verbose_name='更正后责任人')),
                ('old_custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections_from', to=settings.AUTH_USER_MODEL, verbose_name='原责任人')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoff_corrections', to=settings.AUTH_USER_MODEL, verbose_name='更正操作人')),
            ],
            options={
                'verbose_name': '交接更正记录',
                'verbose_name_plural': '交接更正记录',
                'db_table': 'wh_handoff_correction',
                'ordering': ['-created_at'],
            },
        ),
    ]
